/**
 * admin.js
 * Version:     0.1
 * Author:      Green Sheep
 * Created:     June 7, 2018
 * Modified:
 * License:     GPLv2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 */
wirGl_localize = {
  'tench, Tinca tinca' : 'コイ',
  'goldfish, Carassius auratus' : '金魚',
  'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias' : 'ホホジロザメ',
  'tiger shark, Galeocerdo cuvieri' : 'イタチザメ',
  'hammerhead, hammerhead shark' : 'ハンマーヘッドシャーク',
  'electric ray, crampfish, numbfish, torpedo' : 'シビレエイ',
  'stingray' : 'アカエイ',
  'cock' : '雄鶏',
  'hen' : '雌鶏',
  'ostrich, Struthio camelus' : 'ダチョウ',
  'brambling, Fringilla montifringilla' : 'アトリ',
  'goldfinch, Carduelis carduelis' : 'ゴシキヒワ',
  'house finch, linnet, Carpodacus mexicanus' : 'メキシコマシコ',
  'junco, snowbird' : 'ユキヒメドリ',
  'indigo bunting, indigo finch, indigo bird, Passerina cyanea' : 'ルリノジコ',
  'robin, American robin, Turdus migratorius' : 'ツグミ',
  'bulbul' : 'ヒヨドリ',
  'jay' : 'カケス',
  'magpie' : 'カササギ',
  'chickadee' : 'クロイロコガラ',
  'water ouzel, dipper' : 'カワガラス',
  'kite' : 'トビ',
  'bald eagle, American eagle, Haliaeetus leucocephalus' : 'ワシ',
  'vulture' : 'コンドル',
  'great grey owl, great gray owl, Strix nebulosa' : 'フクロウ',
  'European fire salamander, Salamandra salamandra' : 'ファイアサラマンダー',
  'common newt, Triturus vulgaris' : 'スベイモリ',
  'eft' : 'イモリ',
  'spotted salamander, Ambystoma maculatum' : 'サンショウウオ',
  'axolotl, mud puppy, Ambystoma mexicanum' : 'ウーパールーパー',
  'bullfrog, Rana catesbeiana' : 'ウシガエル',
  'tree frog, tree-frog' : 'カエル',
  'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui' : 'ヒキガエル',
  'loggerhead, loggerhead turtle, Caretta caretta' : 'ウミガメ',
  'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea' : 'オサガメ',
  'mud turtle' : 'ドロガメ',
  'terrapin' : 'キスイガメ',
  'box turtle, box tortoise' : 'アメリカハコガメ',
  'banded gecko' : 'ヤモリ',
  'common iguana, iguana, Iguana iguana' : 'イグアナ',
  'American chameleon, anole, Anolis carolinensis' : 'アノールトカゲ',
  'whiptail, whiptail lizard' : 'ハシリトカゲ',
  'agama' : 'アガマ',
  'frilled lizard, Chlamydosaurus kingi' : 'エリマキトカゲ',
  'alligator lizard' : 'ワニトカゲ',
  'Gila monster, Heloderma suspectum' : 'ドクトカゲ',
  'green lizard, Lacerta viridis' : 'ミドリカナヘビ',
  'African chameleon, Chamaeleo chamaeleon' : 'カメレオン',
  'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis' : 'コモド・ドラゴン',
  'African crocodile, Nile crocodile, Crocodylus niloticus' : 'ナイルワニ',
  'American alligator, Alligator mississipiensis' : 'アメリカアリゲーター',
  'triceratops' : 'トリケラトプス',
  'thunder snake, worm snake, Carphophis amoenus' : 'サンダースネーク',
  'ringneck snake, ring-necked snake, ring snake' : 'クビワヘビ',
  'hognose snake, puff adder, sand viper' : 'ホーゴス・ヘビ',
  'green snake, grass snake' : 'アメリカアオヘビ',
  'king snake, kingsnake' : 'キングヘビ',
  'garter snake, grass snake' : 'ガーターヘビ',
  'water snake' : 'ミズベヘビ',
  'vine snake' : 'ハナナガムチヘビ',
  'night snake, Hypsiglena torquata' : 'ナイトスネーク',
  'boa constrictor, Constrictor constrictor' : 'ボアコンストリクター',
  'rock python, rock snake, Python sebae' : 'アフリカニシキヘビ',
  'Indian cobra, Naja naja' : 'インドコブラ',
  'green mamba' : 'ヒガシグリーンマンバ',
  'sea snake' : 'ウミヘビ',
  'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus' : 'サハラツノクサリヘビ',
  'diamondback, diamondback rattlesnake, Crotalus adamanteus' : 'ガラガラヘビ',
  'sidewinder, horned rattlesnake, Crotalus cerastes' : 'ヨコバイガラガラヘビ',
  'trilobite' : '三葉虫',
  'harvestman, daddy longlegs, Phalangium opilio' : 'ザトウムシ',
  'scorpion' : 'サソリ',
  'black and gold garden spider, Argiope aurantia' : 'キマダラコガネグモ',
  'barn spider, Araneus cavaticus' : 'オニグモ',
  'garden spider, Aranea diademata' : 'コガネグモ',
  'black widow, Latrodectus mactans' : 'クロゴケグモ',
  'tarantula' : 'タランチュラ',
  'wolf spider, hunting spider' : 'コモリグモ',
  'tick' : 'ダニ',
  'centipede' : 'ムカデ',
  'black grouse' : 'クロライチョウ',
  'ptarmigan' : '雷鳥',
  'ruffed grouse, partridge, Bonasa umbellus' : 'エリマキライチョウ',
  'prairie chicken, prairie grouse, prairie fowl' : 'ソウゲンライチョウ',
  'peacock' : '孔雀',
  'quail' : 'ウズラ',
  'partridge' : 'ヤマウズラ',
  'African grey, African gray, Psittacus erithacus' : 'ヨウム',
  'macaw' : 'コンゴウインコ',
  'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita' : 'キバタン',
  'lorikeet' : 'ヒインコ',
  'coucal' : 'バンケン',
  'bee eater' : 'ハチクイ',
  'hornbill' : 'サイチョウ',
  'hummingbird' : 'ハチドリ',
  'jacamar' : 'キリハシ',
  'toucan' : 'オオハシ',
  'drake' : '鴨',
  'red-breasted merganser, Mergus serrator' : 'ウミアイサ',
  'goose' : 'ガチョウ',
  'black swan, Cygnus atratus' : 'ブラック・スワン',
  'tusker' : 'ゾウ',
  'echidna, spiny anteater, anteater' : 'ハリモグラ',
  'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus' : 'カモノハシ',
  'wallaby, brush kangaroo' : 'ワラビー',
  'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus' : 'コアラ',
  'wombat' : 'ウォンバット',
  'jelly fish' : 'クラゲ',
  'sea anemone, anemone' : 'イソギンチャク',
  'brain coral' : 'キクメイシ',
  'flatworm, platyhelminth' : '扁形動物',
  'nematode, nematode worm, roundworm' : '線虫',
  'conch' : '巻貝',
  'snail' : 'カタツムリ',
  'slug' : 'なめくじ',
  'sea slug, nudibranch' : 'ウミウシ',
  'chiton, coat-of-mail shell, sea cradle, polyplacophore' : '多板綱',
  'chambered nautilus, pearly nautilus, nautilus' : 'オウムガイ',
  'Dungeness crab, Cancer magister' : 'アメリカイチョウガニ',
  'rock crab, Cancer irroratus' : 'イチョウガニ',
  'fiddler crab' : 'シオマネキ',
  'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica' : 'タラバガニ',
  'American lobster, Northern lobster, Maine lobster, Homarus americanus' : 'アメリカンロブスター',
  'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish' : 'イセエビ',
  'crayfish, crawfish, crawdad, crawdaddy' : 'ザリガニ',
  'hermit crab' : 'ヤドカリ',
  'isopod' : 'ワラジムシ',
  'white stork, Ciconia ciconia' : 'シュバシコウ',
  'black stork, Ciconia nigra' : 'ナベコウ',
  'spoonbill' : 'ヘラサギ',
  'flamingo' : 'フラミンゴ',
  'little blue heron, Egretta caerulea' : 'スミレサギ',
  'American egret, great white heron, Egretta albus' : 'ユキコサギ',
  'bittern' : 'サンカノゴイ',
  'crane' : 'クレーン',
  'limpkin, Aramus pictus' : 'ツルモドキ',
  'European gallinule, Porphyrio porphyrio' : 'クイナ',
  'American coot, marsh hen, mud hen, water hen, Fulica americana' : 'アメリカオオバン',
  'bustard' : 'ノガン',
  'ruddy turnstone, Arenaria interpres' : 'キョウジョシギ',
  'red-backed sandpiper, dunlin, Erolia alpina' : 'ハマシギ',
  'redshank, Tringa totanus' : 'アカアシシギ',
  'dowitcher' : 'オオハシシギ',
  'oystercatcher, oyster catcher' : 'ミヤコドリ',
  'pelican' : 'ペリカン',
  'king penguin, Aptenodytes patagonica' : 'キングペンギン',
  'albatross, mollymawk' : 'アホウドリ',
  'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus' : 'コククジラ',
  'killer whale, killer, orca, grampus, sea wolf, Orcinus orca' : 'シャチ',
  'dugong, Dugong dugon' : 'ジュゴン',
  'sea lion' : 'アシカ',
  'Chihuahua' : 'チワワ',
  'Japanese spaniel' : '狆',
  'Maltese dog, Maltese terrier, Maltese' : 'マルチーズ',
  'Pekinese, Pekingese, Peke' : 'ペキニーズ',
  'Shih-Tzu' : 'シーズー',
  'Blenheim spaniel' : 'キャバリア・キング・チャールズ・スパニエル',
  'papillon' : 'パピヨン',
  'toy terrier' : 'トイ・テリア',
  'Rhodesian ridgeback' : 'ローデシアン・リッジバック',
  'Afghan hound, Afghan' : 'アフガン・ハウンド',
  'basset, basset hound' : 'バセット・ハウンド',
  'beagle' : 'ビーグル',
  'bloodhound, sleuthhound' : 'ブラッドハウンド',
  'bluetick' : 'ブルーティック・クーンハウンド',
  'black-and-tan coonhound' : 'ブラック・アンド・タン・クーンハウンド',
  'Walker hound, Walker foxhound' : 'ツリーイング・ウォーカー・クーンハウンド',
  'English foxhound' : 'イングリッシュ・フォックスハウンド',
  'redbone' : 'レッドボーン・クーンハウンド',
  'borzoi, Russian wolfhound' : 'ボルゾイ',
  'Irish wolfhound' : 'アイリッシュ・ウルフハウンド',
  'Italian greyhound' : 'イタリアン・グレイハウンド',
  'whippet' : 'ウィペット',
  'Ibizan hound, Ibizan Podenco' : 'イビザン・ハウンド',
  'Norwegian elkhound, elkhound' : 'ノルウェジアン・エルクハウンド・グレー',
  'otterhound, otter hound' : 'オッターハウンド',
  'Saluki, gazelle hound' : 'サルーキ',
  'Scottish deerhound, deerhound' : 'スコティッシュ・ディアハウンド',
  'Weimaraner' : 'ワイマラナー',
  'Staffordshire bullterrier, Staffordshire bull terrier' : 'スタッフォードシャー・ブル・テリア',
  'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier' : 'アメリカン・スタッフォードシャー・テリア',
  'Bedlington terrier' : 'ベドリントン・テリア',
  'Border terrier' : 'ボーダー・テリア',
  'Kerry blue terrier' : 'ケリー・ブルー・テリア',
  'Irish terrier' : 'アイリッシュ・テリア',
  'Norfolk terrier' : 'ノーフォーク・テリア',
  'Norwich terrier' : 'ノーリッチ・テリア',
  'Yorkshire terrier' : 'ヨークシャーテリア',
  'wire-haired fox terrier' : 'ワイアー・フォックス・テリア',
  'Lakeland terrier' : 'レークランド・テリア',
  'Sealyham terrier, Sealyham' : 'シーリハム・テリア',
  'Airedale, Airedale terrier' : 'エアデール・テリア',
  'cairn, cairn terrier' : 'ケアーン・テリア',
  'Australian terrier' : 'オーストラリアン・テリア',
  'Dandie Dinmont, Dandie Dinmont terrier' : 'ダンディ・ディンモント・テリア',
  'Boston bull, Boston terrier' : 'ボストン・テリア',
  'miniature schnauzer' : 'ミニチュア・シュナウザー',
  'giant schnauzer' : 'ジャイアント・シュナウザー',
  'standard schnauzer' : 'スタンダード・シュナウザー',
  'Scotch terrier, Scottish terrier, Scottie' : 'スコティッシュ・テリア',
  'Tibetan terrier, chrysanthemum dog' : 'チベタン・テリア',
  'silky terrier, Sydney silky' : 'オーストラリアン・シルキー・テリア',
  'soft-coated wheaten terrier' : 'ソフトコーテッド・ウィートン・テリア',
  'West Highland white terrier' : 'ウエスト・ハイランド・ホワイト・テリア',
  'Lhasa, Lhasa apso' : 'ラサ・アプソ',
  'flat-coated retriever' : 'フラットコーテッド・レトリーバー',
  'curly-coated retriever' : 'カーリーコーテッド・レトリーバー',
  'golden retriever' : 'ゴールデンレトリバー',
  'Labrador retriever' : 'ラブラドール・レトリバー',
  'Chesapeake Bay retriever' : 'チェサピーク・ベイ・レトリーバー',
  'German short-haired pointer' : 'ジャーマン・ショートヘアード・ポインター',
  'vizsla, Hungarian pointer' : 'ショートヘアード・ハンガリアン・ビズラ',
  'English setter' : 'イングリッシュ・セター',
  'Irish setter, red setter' : 'アイリッシュ・セッター',
  'Gordon setter' : 'ゴードン・セッター',
  'Brittany spaniel' : 'ブリタニー・スパニエル',
  'clumber, clumber spaniel' : 'クランバー・スパニエル',
  'English springer, English springer spaniel' : 'イングリッシュ・スプリンガー・スパニエル',
  'Welsh springer spaniel' : 'ウェルシュ・スプリンガー・スパニエル',
  'cocker spaniel, English cocker spaniel, cocker' : 'コッカー・スパニエル',
  'Sussex spaniel' : 'サセックス・スパニエル',
  'Irish water spaniel' : 'アイリッシュ・ウォーター・スパニエル',
  'kuvasz' : 'クーバース',
  'schipperke' : 'スキッパーキ',
  'groenendael' : 'ベルジアン・シェパード・ドッグ・グローネンダール',
  'malinois' : 'ベルジアン・シェパード・ドッグ・マリノア',
  'briard' : 'ブリアード',
  'kelpie' : 'ケルピー',
  'komondor' : 'コモンドール',
  'Old English sheepdog, bobtail' : 'オールド・イングリッシュ・シープドッグ',
  'Shetland sheepdog, Shetland sheep dog, Shetland' : 'シェットランド・シープドッグ',
  'collie' : 'コリー',
  'Border collie' : 'ボーダー・コリー',
  'Bouvier des Flandres, Bouviers des Flandres' : 'ブービエ・デ・フランダース',
  'Rottweiler' : 'ロットワイラー',
  'German shepherd, German shepherd dog, German police dog, alsatian' : 'ジャーマン・シェパード・ドッグ',
  'Doberman, Doberman pinscher' : 'ドーベルマン',
  'miniature pinscher' : 'ミニチュア・ピンシャー',
  'Greater Swiss Mountain dog' : 'グレーター・スイス・マウンテン・ドッグ',
  'Bernese mountain dog' : 'バーニーズ・マウンテン・ドッグ',
  'Appenzeller' : 'アッペンツェラー・キャトル・ドッグ',
  'EntleBucher' : 'エントレブッハー・キャトル・ドッグ',
  'boxer' : 'ボクサー',
  'bull mastiff' : 'ブルマスティフ',
  'Tibetan mastiff' : 'チベタン・マスティフ',
  'French bulldog' : 'フレンチ・ブルドッグ',
  'Great Dane' : 'グレート・デーン',
  'Saint Bernard, St Bernard' : 'セントバーナード',
  'Eskimo dog, husky' : 'エスキモー・ドッグ',
  'malamute, malemute, Alaskan malamute' : 'アラスカン・マラミュート',
  'Siberian husky' : 'シベリアンハスキー',
  'dalmatian, coach dog, carriage dog' : 'ダルメシアン',
  'affenpinscher, monkey pinscher, monkey dog' : 'アーフェンピンシャー',
  'basenji' : 'バセンジー',
  'pug, pug-dog' : 'パグ',
  'Leonberg' : 'レオンベルガー',
  'Newfoundland, Newfoundland dog' : 'ニューファンドランド',
  'Great Pyrenees' : 'グレート・ピレニーズ',
  'Samoyed, Samoyede' : 'サモエド',
  'Pomeranian' : 'ポメラニアン',
  'chow, chow chow' : 'チャウ・チャウ',
  'keeshond' : 'キースホンド',
  'Brabancon griffon' : 'ブリュッセル・グリフォン',
  'Pembroke, Pembroke Welsh corgi' : 'コーギー',
  'Cardigan, Cardigan Welsh corgi' : 'ウェルシュ・コーギー・カーディガン',
  'toy poodle' : 'トイプードル',
  'miniature poodle' : 'ミニチュアプードル',
  'standard poodle' : 'スタンダード・プードル',
  'Mexican hairless' : 'メキシカン・ヘアレス・ドッグ',
  'timber wolf, grey wolf, gray wolf, Canis lupus' : 'タイリクオオカミ',
  'white wolf, Arctic wolf, Canis lupus tundrarum' : 'ホッキョクオオカミ',
  'red wolf, maned wolf, Canis rufus, Canis niger' : 'アメリカアカオオカミ',
  'coyote, prairie wolf, brush wolf, Canis latrans' : 'コヨーテ',
  'dingo, warrigal, warragal, Canis dingo' : 'ディンゴ',
  'dhole, Cuon alpinus' : 'ドール',
  'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus' : 'リカオン',
  'hyena, hyaena' : 'ハイエナ',
  'red fox, Vulpes vulpes' : 'アカギツネ',
  'kit fox, Vulpes macrotis' : 'キットギツネ',
  'Arctic fox, white fox, Alopex lagopus' : 'ホッキョクギツネ',
  'grey fox, gray fox, Urocyon cinereoargenteus' : 'ハイイロギツネ',
  'tabby, tabby cat' : 'トラネコ',
  'tiger cat' : 'ジャガーネコ',
  'Persian cat' : 'ペルシャ猫',
  'Siamese cat, Siamese' : 'シャム猫',
  'Egyptian cat' : 'エジプシャンマウ',
  'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor' : 'ピューマ',
  'lynx, catamount' : 'オオヤマネコ',
  'leopard, Panthera pardus' : 'ヒョウ',
  'snow leopard, ounce, Panthera uncia' : 'ユキヒョウ',
  'jaguar, panther, Panthera onca, Felis onca' : 'ジャガー',
  'lion, king of beasts, Panthera leo' : 'ライオン',
  'tiger, Panthera tigris' : 'トラ',
  'cheetah, chetah, Acinonyx jubatus' : 'チーター',
  'brown bear, bruin, Ursus arctos' : 'ヒグマ',
  'American black bear, black bear, Ursus americanus, Euarctos americanus' : 'アメリカグマ',
  'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus' : 'ホッキョクグマ',
  'sloth bear, Melursus ursinus, Ursus ursinus' : 'ナマケグマ',
  'mongoose' : 'マングース',
  'meerkat, mierkat' : 'ミーアキャット',
  'tiger beetle' : 'ハンミョウ',
  'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle' : 'てんとう虫',
  'ground beetle, carabid beetle' : 'オサムシ',
  'long-horned beetle, longicorn, longicorn beetle' : 'ゴマダラカミキリ',
  'leaf beetle, chrysomelid' : 'ハムシ',
  'dung beetle' : 'フンコロガシ',
  'rhinoceros beetle' : 'カブトムシ',
  'weevil' : 'ゾウムシ',
  'fly' : 'ハエ',
  'bee' : '蜂',
  'ant, emmet, pismire' : 'アリ',
  'grasshopper, hopper' : 'バッタ',
  'cricket' : 'クリケット',
  'walking stick, walkingstick, stick insect' : 'ナナフシ',
  'cockroach, roach' : 'ゴキブリ',
  'mantis, mantid' : 'カマキリ',
  'cicada, cicala' : 'セミ',
  'leafhopper' : 'ヨコバイ',
  'lacewing, lacewing fly' : 'クサカゲロウ',
  'dragonfly, darning needle, devil\'s darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk' : 'トンボ',
  'damselfly' : 'イトトンボ',
  'admiral' : 'アカタテハ',
  'ringlet, ringlet butterfly' : 'チョウセンジャノメ',
  'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus' : 'オオカバマダラ',
  'cabbage butterfly' : 'オオモンシロチョウ',
  'sulphur butterfly, sulfur butterfly' : '硫黄蝶',
  'lycaenid, lycaenid butterfly' : 'シジミチョウ',
  'starfish, sea star' : 'ヒトデ',
  'sea urchin' : 'うに',
  'sea cucumber, holothurian' : 'ナマコ',
  'wood rabbit, cottontail, cottontail rabbit' : 'ワタオウサギ',
  'hare' : '野ウサギ',
  'Angora, Angora rabbit' : 'アンゴラウサギ',
  'hamster' : 'ハムスター',
  'porcupine, hedgehog' : 'ヤマアラシ',
  'fox squirrel, eastern fox squirrel, Sciurus niger' : 'キツネリス',
  'marmot' : 'マーモット',
  'beaver' : 'ビーバー',
  'guinea pig, Cavia cobaya' : 'モルモット',
  'sorrel' : '栗毛馬',
  'zebra' : 'シマウマ',
  'hog, pig, grunter, squealer, Sus scrofa' : '豚',
  'wild boar, boar, Sus scrofa' : 'イノシシ',
  'warthog' : 'イボイノシシ',
  'hippopotamus, hippo, river horse, Hippopotamus amphibius' : 'カバ',
  'ox' : '雄牛',
  'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis' : '水牛',
  'bison' : 'バイソン',
  'ram, tup' : '雄羊',
  'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis' : 'ビッグホーン',
  'ibex, Capra ibex' : 'アイベックス',
  'hartebeest' : 'ハーテビースト',
  'impala, Aepyceros melampus' : 'インパラ',
  'gazelle' : 'ガゼル',
  'Arabian camel, dromedary, Camelus dromedarius' : 'ヒトコブラクダ',
  'llama' : 'リャマ',
  'weasel' : 'イタチ',
  'mink' : 'ミンク',
  'polecat, fitch, foulmart, foumart, Mustela putorius' : 'ヨーロッパケナガイタチ',
  'black-footed ferret, ferret, Mustela nigripes' : 'フェレット',
  'otter' : 'カワウソ',
  'skunk, polecat, wood pussy' : 'スカンク',
  'badger' : '狸',
  'armadillo' : 'アルマジロ',
  'three-toed sloth, ai, Bradypus tridactylus' : 'ミユビナマケモノ',
  'orangutan, orang, orangutang, Pongo pygmaeus' : 'オランウータン',
  'gorilla, Gorilla gorilla' : 'ゴリラ',
  'chimpanzee, chimp, Pan troglodytes' : 'チンパンジー',
  'gibbon, Hylobates lar' : 'テナガザル',
  'siamang, Hylobates syndactylus, Symphalangus syndactylus' : 'フクロテナガザル',
  'guenon, guenon monkey' : 'グエノン',
  'patas, hussar monkey, Erythrocebus patas' : 'パタスモンキー',
  'baboon' : 'ヒヒ',
  'macaque' : 'マカク',
  'langur' : 'ハヌマンラングール',
  'colobus, colobus monkey' : 'コロブスサル',
  'proboscis monkey, Nasalis larvatus' : 'テングザル',
  'marmoset' : 'マーモセット',
  'capuchin, ringtail, Cebus capucinus' : 'オマキザル',
  'howler monkey, howler' : 'ホエザル',
  'titi, titi monkey' : 'ティティサル',
  'spider monkey, Ateles geoffroyi' : 'クモザル',
  'squirrel monkey, Saimiri sciureus' : 'リスザル',
  'Madagascar cat, ring-tailed lemur, Lemur catta' : 'ワオキツネザル',
  'indri, indris, Indri indri, Indri brevicaudatus' : 'インドリ',
  'Indian elephant, Elephas maximus' : 'インドゾウ',
  'African elephant, Loxodonta africana' : 'アフリカゾウ',
  'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens' : 'レッサーパンダ',
  'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca' : 'パンダ',
  'barracouta, snoek' : 'バラクーダ',
  'eel' : 'ウナギ',
  'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch' : 'ギンザケ',
  'rock beauty, Holocanthus tricolor' : 'ロック･ビューティー',
  'anemone fish' : 'クマノミ',
  'sturgeon' : 'チョウザメ',
  'gar, garfish, garpike, billfish, Lepisosteus osseus' : 'ダツ',
  'lionfish' : 'ミノカサゴ',
  'puffer, pufferfish, blowfish, globefish' : 'フグ',
  'abacus' : 'そろばん',
  'abaya' : 'アバヤ',
  'academic gown, academic robe, judge\'s robe' : 'アカデミックドレス',
  'accordion, piano accordion, squeeze box' : 'アコーディオン',
  'acoustic guitar' : 'アコースティックギター',
  'aircraft carrier, carrier, flattop, attack aircraft carrier' : '空母',
  'airliner' : '旅客機',
  'airship, dirigible' : '飛行船、飛行船',
  'altar' : '祭壇',
  'ambulance' : '救急車',
  'amphibian, amphibious vehicle' : '水陸両用車',
  'analog clock' : 'アナログ時計',
  'apiary, bee house' : '養蜂場',
  'apron' : 'エプロン',
  'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin' : 'ごみ箱',
  'assault rifle, assault gun' : 'アサルトライフル',
  'backpack, back pack, knapsack, packsack, rucksack, haversack' : 'バックパック',
  'bakery, bakeshop, bakehouse' : 'ベーカリー',
  'balance beam, beam' : '平均台',
  'balloon' : 'バルーン',
  'ballpoint, ballpoint pen, ballpen, Biro' : 'ボールペン',
  'Band Aid' : 'バンドエイド',
  'banjo' : 'バンジョー',
  'bannister, banister, balustrade, balusters, handrail' : '手すり',
  'barbell' : 'バーベル',
  'barber chair' : '理髪椅子',
  'barbershop' : '理髪店',
  'barn' : '納屋',
  'barometer' : '気圧計',
  'barrel, cask' : 'たる',
  'barrow, garden cart, lawn cart, wheelbarrow' : '手押し車',
  'baseball' : '野球',
  'basketball' : 'バスケットボール',
  'bassinet' : '新生児用ベッド',
  'bassoon' : 'ファゴット',
  'bathing cap, swimming cap' : '水泳用キャップ',
  'bath towel' : 'バスタオル',
  'bathtub, bathing tub, bath, tub' : '浴槽',
  'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon' : 'ステーションワゴン',
  'beacon, lighthouse, beacon light, pharos' : '灯台',
  'beaker' : 'ビーカー',
  'bearskin, busby, shako' : '黒毛皮帽',
  'beer bottle' : 'ビール瓶',
  'beer glass' : 'ビールグラス',
  'bell cote, bell cot' : '鐘つり塔',
  'bib' : 'よだれかけ',
  'bicycle-built-for-two, tandem bicycle, tandem' : 'タンデム自転車',
  'bikini, two-piece' : 'ビキニ',
  'binder, ring-binder' : 'バインダー',
  'binoculars, field glasses, opera glasses' : '双眼鏡',
  'birdhouse' : '小鳥小屋',
  'boathouse' : '舟小屋',
  'bobsled, bobsleigh, bob' : 'ボブスレー',
  'bolo tie, bolo, bola tie, bola' : 'ポーラー・タイ',
  'bonnet, poke bonnet' : 'ポークボンネット',
  'bookcase' : '本棚',
  'bookshop, bookstore, bookstall' : '書店',
  'bottlecap' : '瓶のキャップ',
  'bow' : '蝶形リボン',
  'bow tie, bow-tie, bowtie' : 'ちょうネクタイ',
  'brass, memorial tablet, plaque' : '記念碑',
  'brassiere, bra, bandeau' : 'ブラジャー',
  'breakwater, groin, groyne, mole, bulwark, seawall, jetty' : '防波堤',
  'breastplate, aegis, egis' : '胸当て',
  'broom' : 'ほうき',
  'bucket, pail' : 'バケツ',
  'buckle' : 'バックル',
  'bulletproof vest' : '防弾チョッキ',
  'bullet train, bullet' : '新幹線',
  'butcher shop, meat market' : '食肉市場',
  'cab, hack, taxi, taxicab' : 'タクシー',
  'caldron, cauldron' : '大釜',
  'candle, taper, wax light' : 'キャンドル',
  'cannon' : '大砲',
  'canoe' : 'カヌー',
  'can opener, tin opener' : '缶切り',
  'cardigan' : 'カーディガン',
  'car mirror' : 'サイドミラー',
  'carousel, carrousel, merry-go-round, roundabout, whirligig' : 'メリーゴーランド',
  'carpenter\'s kit, tool kit' : '大工用キット',
  'carton' : '段ボール',
  'car wheel' : '車輪',
  'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM' : 'ATM',
  'cassette' : 'カセット',
  'cassette player' : 'カセット・プレーヤー',
  'castle' : '城',
  'catamaran' : '双胴船',
  'CD player' : 'CDプレーヤー',
  'cello, violoncello' : 'チェロ',
  'cellular telephone, cellular phone, cellphone, cell, mobile phone' : '携帯電話',
  'chain' : '鎖',
  'chainlink fence' : '金網フェンス',
  'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour' : 'リングアーマー',
  'chain saw, chainsaw' : 'チェーンソー',
  'chest' : '箱',
  'chiffonier, commode' : 'たんす',
  'chime, bell, gong' : 'ベル',
  'china cabinet, china closet' : '食器棚',
  'Christmas stocking' : 'クリスマス・ストッキング',
  'church, church building' : '教会',
  'cinema, movie theater, movie theatre, movie house, picture palace' : '映画館',
  'cleaver, meat cleaver, chopper' : 'なた',
  'cliff dwelling' : '崖住居',
  'cloak' : 'マント',
  'clog, geta, patten, sabot' : '木靴',
  'cocktail shaker' : 'カクテルシェーカー',
  'coffee mug' : 'コーヒーマグカップ',
  'coffeepot' : 'コーヒーポット',
  'coil, spiral, volute, whorl, helix' : 'らせん階段',
  'combination lock' : 'ダイヤル錠',
  'computer keyboard, keypad' : 'キーボード',
  'confectionery, confectionary, candy store' : 'キャンディー・ストア',
  'container ship, containership, container vessel' : 'コンテナ船',
  'convertible' : 'コンバーチブル',
  'corkscrew, bottle screw' : 'コルクスクリュー、ボトルスクリュー',
  'cornet, horn, trumpet, trump' : 'トランペット',
  'cowboy boot' : 'カウボーイブーツ',
  'cowboy hat, ten-gallon hat' : 'テンガロンハット',
  'cradle' : 'ゆりかご',
  'crane' : 'クレーン',
  'crash helmet' : 'クラッシュ・ヘルメット',
  'crate' : '木箱',
  'crib, cot' : 'ベビーベッド',
  'Crock Pot' : '調理鍋',
  'croquet ball' : 'クロケットボール',
  'crutch' : '松葉杖',
  'cuirass' : '胴よろい',
  'dam, dike, dyke' : 'ダム',
  'desk' : '机',
  'desktop computer' : 'デスクトップコンピューター',
  'dial telephone, dial phone' : 'ダイヤル電話',
  'diaper, nappy, napkin' : 'おむつ',
  'digital clock' : 'デジタル時計',
  'digital watch' : 'デジタル腕時計',
  'dining table, board' : 'ダイニングテーブル',
  'dishrag, dishcloth' : 'ヘチマ布巾',
  'dishwasher, dish washer, dishwashing machine' : '食器洗い機',
  'disk brake, disc brake' : 'ディスクブレーキ',
  'dock, dockage, docking facility' : 'ドック',
  'dogsled, dog sled, dog sleigh' : '犬ぞり',
  'dome' : 'ドーム',
  'doormat, welcome mat' : 'ドアマット',
  'drilling platform, offshore rig' : '掘削プラットホーム',
  'drum, membranophone, tympan' : 'ドラム',
  'drumstick' : 'ドラムスティック',
  'dumbbell' : 'ダンベル',
  'Dutch oven' : 'ダッチオーブン',
  'electric fan, blower' : '扇風機',
  'electric guitar' : 'エレキギター',
  'electric locomotive' : '電気機関車',
  'entertainment center' : 'エンターテインメント・センター家具',
  'envelope' : '封筒',
  'espresso maker' : 'エスプレッソメーカー',
  'face powder' : 'おしろい',
  'feather boa, boa' : 'ボア',
  'file, file cabinet, filing cabinet' : '書類整理棚',
  'fireboat' : '消防船',
  'fire engine, fire truck' : '消防車',
  'fire screen, fireguard' : '防火柵',
  'flagpole, flagstaff' : 'フラッグポール',
  'flute, transverse flute' : 'フルート',
  'folding chair' : '折りたたみ椅子',
  'football helmet' : 'フットボールヘルメット',
  'forklift' : 'フォークリフト',
  'fountain' : '噴水',
  'fountain pen' : '万年筆',
  'four-poster' : ' 四柱式ベッド',
  'freight car' : '貨車',
  'French horn, horn' : 'ホルン',
  'frying pan, frypan, skillet' : 'フライパン',
  'fur coat' : '毛皮コート',
  'garbage truck, dustcart' : 'ゴミ収集車',
  'gasmask, respirator, gas helmet' : 'ガスマスク',
  'gas pump, gasoline pump, petrol pump, island dispenser' : 'ガソリンポンプ',
  'goblet' : '聖爵',
  'go-kart' : 'ゴーカート',
  'golf ball' : 'ゴルフボール',
  'golfcart, golf cart' : 'ゴルフカート',
  'gondola' : 'ゴンドラ',
  'gong, tam-tam' : 'ゴング',
  'gown' : 'ガウン',
  'grand piano, grand' : 'グランドピアノ',
  'greenhouse, nursery, glasshouse' : '温室',
  'grille, radiator grille' : 'フロントグリル',
  'grocery store, grocery, food market, market' : '食品市場',
  'guillotine' : 'ギロチン',
  'hair slide' : 'ヘアクリップ',
  'hair spray' : 'ヘアスプレー',
  'half track' : '半装軌車',
  'hammer' : 'ハンマー',
  'hamper' : 'バスケット',
  'hand blower, blow dryer, blow drier, hair dryer, hair drier' : 'ヘアドライヤー',
  'hand-held computer, hand-held microcomputer' : 'ハンドヘルドコンピュータ',
  'handkerchief, hankie, hanky, hankey' : 'ハンカチ',
  'hard disc, hard disk, fixed disk' : 'ハードディスク',
  'harmonica, mouth organ, harp, mouth harp' : 'ハーモニカ',
  'harp' : 'ハープ',
  'harvester, reaper' : 'ハーベスター',
  'hatchet' : '手斧',
  'holster' : '銃ケース',
  'home theater, home theatre' : 'ホームシアター',
  'honeycomb' : 'ハニカム構造',
  'hook, claw' : 'かぎ爪',
  'hoopskirt, crinoline' : 'フープスキート',
  'horizontal bar, high bar' : '鉄棒',
  'horse cart, horse-cart' : '馬車',
  'hourglass' : '砂時計',
  'iPod' : 'iPod',
  'iron, smoothing iron' : 'アイロン',
  'jack-o\'-lantern' : 'ジャック・オー・ランタン',
  'jean, blue jean, denim' : 'ジーンズ',
  'jeep, landrover' : 'ジープ',
  'jersey, T-shirt, tee shirt' : 'Tシャツ',
  'jigsaw puzzle' : 'ジグソーパズル',
  'jinrikisha, ricksha, rickshaw' : '人力車',
  'joystick' : 'ジョイスティック',
  'kimono' : '着物',
  'knee pad' : '膝パッド',
  'knot' : '結び目',
  'lab coat, laboratory coat' : '白衣',
  'ladle' : 'おたま',
  'lampshade, lamp shade' : 'ランプのかさ',
  'laptop, laptop computer' : 'ラップトップコンピュータ',
  'lawn mower, mower' : '芝刈機',
  'lens cap, lens cover' : 'レンズキャップ',
  'letter opener, paper knife, paperknife' : 'ペーパーナイフ',
  'library' : '図書館',
  'lifeboat' : '救命艇',
  'lighter, light, igniter, ignitor' : 'ライター',
  'limousine, limo' : 'リムジン',
  'liner, ocean liner' : 'オーシャン・ライナー',
  'lipstick, lip rouge' : '口紅',
  'Loafer' : 'ローファー',
  'lotion' : 'ローション',
  'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system' : 'スピーカー',
  'loupe, jeweler\'s loupe' : 'ルーペ',
  'lumbermill, sawmill' : '製材所',
  'magnetic compass' : '方位磁針',
  'mailbag, postbag' : 'メールバッグ',
  'mailbox, letter box' : '郵便受け',
  'maillot' : 'レオタード',
  'maillot, tank suit' : 'ワンピース水着',
  'manhole cover' : 'マンホールカバー',
  'maraca' : 'マラカス',
  'marimba, xylophone' : 'マリンバ',
  'mask' : '仮面',
  'matchstick' : 'マッチ棒',
  'maypole' : 'メイポール',
  'maze, labyrinth' : '迷路',
  'measuring cup' : '計量カップ',
  'medicine chest, medicine cabinet' : '薬箱',
  'megalith, megalithic structure' : '巨石構造',
  'microphone, mike' : 'マイク',
  'microwave, microwave oven' : '電子レンジ',
  'military uniform' : '軍服',
  'milk can' : 'ミルク缶',
  'minibus' : 'マイクロバス',
  'miniskirt, mini' : 'ミニスカート',
  'minivan' : 'ミニバン',
  'missile' : 'ミサイル',
  'mitten' : 'ミトン',
  'mixing bowl' : 'ミキサーボウル',
  'mobile home, manufactured home' : 'トレーラーハウス',
  'Model T' : 'フォード・モデルT',
  'modem' : 'モデム',
  'monastery' : '修道院',
  'monitor' : 'モニター',
  'moped' : 'モペッド',
  'mortar' : 'すり鉢',
  'mortarboard' : '式帽',
  'mosque' : 'モスク',
  'mosquito net' : '天蓋',
  'motor scooter, scooter' : 'スクーター',
  'mountain bike, all-terrain bike, off-roader' : 'マウンテンバイク',
  'mountain tent' : 'テント',
  'mouse, computer mouse' : 'マウス',
  'mousetrap' : 'ネズミ捕り',
  'moving van' : '引っ越しトラック',
  'muzzle' : '口輪',
  'nail' : '釘',
  'neck brace' : 'ネックカラー',
  'necklace' : 'ネックレス',
  'nipple' : 'ほ乳瓶',
  'notebook, notebook computer' : 'ノートブックコンピュータ',
  'obelisk' : 'オベリスク',
  'oboe, hautboy, hautbois' : 'オーボエ',
  'ocarina, sweet potato' : 'オカリナ',
  'odometer, hodometer, mileometer, milometer' : '走行距離計',
  'oil filter' : 'オイルフィルター',
  'organ, pipe organ' : 'パイプオルガン',
  'oscilloscope, scope, cathode-ray oscilloscope, CRO' : 'オシロスコープ',
  'overskirt' : 'スカート',
  'oxcart' : '牛車',
  'oxygen mask' : '酸素マスク',
  'packet' : '小包',
  'paddle, boat paddle' : 'パドル',
  'paddlewheel, paddle wheel' : '外輪',
  'padlock' : '南京錠',
  'paintbrush' : '絵筆',
  'pajama, pyjama, pj\'s, jammies' : 'パジャマ',
  'palace' : '宮殿',
  'panpipe, pandean pipe, syrinx' : 'パンパイプ',
  'paper towel' : 'ペーパータオル',
  'parachute, chute' : 'パラシュート',
  'parallel bars, bars' : '平行棒',
  'park bench' : '公園のベンチ',
  'parking meter' : 'パーキングメーター',
  'passenger car, coach, carriage' : '客車',
  'patio, terrace' : 'テラス',
  'pay-phone, pay-station' : '公衆電話',
  'pedestal, plinth, footstall' : '台座',
  'pencil box, pencil case' : '鉛筆ケース',
  'pencil sharpener' : '鉛筆削り',
  'perfume, essence' : '香水',
  'Petri dish' : 'シャーレ',
  'photocopier' : 'コピー機',
  'pick, plectrum, plectron' : 'ピック',
  'pickelhaube' : 'ピッケルハウベ',
  'picket fence, paling' : '囲い柵',
  'pickup, pickup truck' : 'ピックアップトラック',
  'pier' : '埠頭',
  'piggy bank, penny bank' : '貯金箱',
  'pill bottle' : '薬瓶',
  'pillow' : '枕',
  'ping-pong ball' : 'ピンポン球',
  'pinwheel' : '風車',
  'pirate, pirate ship' : '海賊船',
  'pitcher, ewer' : 'ピッチャー',
  'plane, carpenter\'s plane, woodworking plane' : 'かんな',
  'planetarium' : 'プラネタリウム',
  'plastic bag' : 'ビニール袋',
  'plate rack' : 'プレートラック',
  'plow, plough' : '耕運機',
  'plunger, plumber\'s helper' : 'ラバーカップ',
  'Polaroid camera, Polaroid Land camera' : 'ポラロイドカメラ',
  'pole' : '電柱',
  'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria' : '警察バン',
  'poncho' : 'ポンチョ',
  'pool table, billiard table, snooker table' : 'ビリヤードテーブル',
  'pop bottle, soda bottle' : '炭酸飲料',
  'pot, flowerpot' : '植木鉢',
  'potter\'s wheel' : 'ろくろ',
  'power drill' : 'パワードリル',
  'prayer rug, prayer mat' : '礼拝用敷物',
  'printer' : 'プリンタ',
  'prison, prison house' : '刑務所',
  'projectile, missile' : 'ミサイル',
  'projector' : 'プロジェクター',
  'puck, hockey puck' : 'アイスホッケーパック',
  'punching bag, punch bag, punching ball, punchball' : 'サンドバッグ',
  'purse' : '財布',
  'quill, quill pen' : '羽根ペン',
  'quilt, comforter, comfort, puff' : 'キルト',
  'racer, race car, racing car' : 'レースカー',
  'racket, racquet' : 'ラケット',
  'radiator' : 'ラジエーター',
  'radio, wireless' : '無線',
  'radio telescope, radio reflector' : '電波望遠鏡',
  'rain barrel' : '天水桶',
  'recreational vehicle, RV, R.V.' : 'キャンピングカー',
  'reel' : 'リール',
  'reflex camera' : '一眼レフ',
  'refrigerator, icebox' : '冷蔵庫',
  'remote control, remote' : 'リモコン',
  'restaurant, eating house, eating place, eatery' : 'レストラン',
  'revolver, six-gun, six-shooter' : '回転式拳銃',
  'rifle' : 'ライフル',
  'rocking chair, rocker' : 'ロッキングチェア',
  'rotisserie' : '回転肉焼き器',
  'rubber eraser, rubber, pencil eraser' : '消しゴム',
  'rugby ball' : 'ラグビーボール',
  'rule, ruler' : '定規',
  'running shoe' : 'ランニングシューズ',
  'safe' : '金庫',
  'safety pin' : '安全ピン',
  'saltshaker, salt shaker' : '塩入れ',
  'sandal' : 'サンダル',
  'sarong' : 'サロン',
  'sax, saxophone' : 'サックス',
  'scabbard' : 'サヤ',
  'scale, weighing machine' : '計量機',
  'school bus' : 'スクールバス',
  'schooner' : 'スクーナー',
  'scoreboard' : 'スコアボード',
  'screen, CRT screen' : 'CRT画面',
  'screw' : 'ねじ',
  'screwdriver' : 'ドライバー',
  'seat belt, seatbelt' : 'シートベルト',
  'sewing machine' : 'ミシン',
  'shield, buckler' : '盾',
  'shoe shop, shoe-shop, shoe store' : '靴屋',
  'shoji' : '障子',
  'shopping basket' : '買い物かご',
  'shopping cart' : 'ショッピングカート',
  'shovel' : 'シャベル',
  'shower cap' : 'シャワーキャップ',
  'shower curtain' : 'シャワーカーテン',
  'ski' : 'スキー',
  'ski mask' : '目出し帽',
  'sleeping bag' : '寝袋',
  'slide rule, slipstick' : '計算尺',
  'sliding door' : '引き戸',
  'slot, one-armed bandit' : 'スロット',
  'snorkel' : 'シュノーケル',
  'snowmobile' : 'スノーモービル',
  'snowplow, snowplough' : '除雪車',
  'soap dispenser' : 'ソープ・ディスペンサー',
  'soccer ball' : 'サッカーボール',
  'sock' : '靴下',
  'solar dish, solar collector, solar furnace' : '太陽炉',
  'sombrero' : 'ソンブレロ',
  'soup bowl' : 'スープボール',
  'space bar' : 'スペースキー',
  'space heater' : 'スペースヒーター',
  'space shuttle' : 'スペースシャトル',
  'spatula' : 'へら',
  'speedboat' : 'モーターボート',
  'spider web, spider\'s web' : 'クモの巣',
  'spindle' : '紡錘',
  'sports car, sport car' : 'スポーツカー',
  'spotlight, spot' : 'スポットライト',
  'stage' : 'ステージ',
  'steam locomotive' : '蒸気機関車',
  'steel arch bridge' : '鋼アーチ橋',
  'steel drum' : 'スチールドラム',
  'stethoscope' : '聴診器',
  'stole' : 'ストール',
  'stone wall' : '石垣',
  'stopwatch, stop watch' : 'ストップウォッチ',
  'stove' : 'ストーブ',
  'strainer' : '濾過器',
  'streetcar, tram, tramcar, trolley, trolley car' : '路面電車',
  'stretcher' : 'ストレッチャー',
  'studio couch, day bed' : 'ソファベッド',
  'stupa, tope' : '卒塔婆',
  'submarine, pigboat, sub, U-boat' : '潜水艦',
  'suit, suit of clothes' : 'スーツ',
  'sundial' : '日時計',
  'sunglass' : 'サングラス',
  'sunglasses, dark glasses, shades' : 'サングラス',
  'sunscreen, sunblock, sun blocker' : '日焼け止め',
  'suspension bridge' : '吊橋',
  'swab, swob, mop' : 'モップ',
  'sweatshirt' : 'トレーナー',
  'swimming trunks, bathing trunks' : '水着',
  'swing' : 'ブランコ',
  'switch, electric switch, electrical switch' : '電気スイッチ',
  'syringe' : '注射器',
  'table lamp' : '電気スタンド',
  'tank, army tank, armored combat vehicle, armoured combat vehicle' : '装甲戦車',
  'tape player' : 'テーププレーヤー',
  'teapot' : 'ティーポット',
  'teddy, teddy bear' : 'テディベア',
  'television, television system' : 'テレビ',
  'tennis ball' : 'テニスボール',
  'thatch, thatched roof' : '茅葺き屋根',
  'theater curtain, theatre curtain' : 'シアターカーテン',
  'thimble' : '指ぬき',
  'thresher, thrasher, threshing machine' : '脱穀機',
  'throne' : '王座',
  'tile roof' : '瓦屋根',
  'toaster' : 'トースター',
  'tobacco shop, tobacconist shop, tobacconist' : 'タバコ屋',
  'toilet seat' : '便座',
  'torch' : 'トーチ',
  'totem pole' : 'トーテムポール',
  'tow truck, tow car, wrecker' : 'レッカー車',
  'toyshop' : '玩具屋',
  'tractor' : 'トラクター',
  'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi' : 'トレーラー',
  'tray' : 'トレイ',
  'trench coat' : 'トレンチコート',
  'tricycle, trike, velocipede' : '三輪車',
  'trimaran' : '三胴船',
  'tripod' : '三脚',
  'triumphal arch' : '凱旋門',
  'trolleybus, trolley coach, trackless trolley' : 'トロリーバス',
  'trombone' : 'トロンボーン',
  'tub, vat' : '浴槽',
  'turnstile' : '改札口',
  'typewriter keyboard' : 'タイプライターキーボード',
  'umbrella' : '傘',
  'unicycle, monocycle' : '一輪車',
  'upright, upright piano' : 'アップライトピアノ',
  'vacuum, vacuum cleaner' : '掃除機',
  'vase' : '花瓶',
  'vault' : 'アーチ形天井',
  'velvet' : 'ベルベット',
  'vending machine' : '自動販売機',
  'vestment' : '祭服',
  'viaduct' : '高架橋',
  'violin, fiddle' : 'バイオリン',
  'volleyball' : 'バレーボール',
  'waffle iron' : 'ワッフル焼き型',
  'wall clock' : '壁時計',
  'wallet, billfold, notecase, pocketbook' : 'お札入れ',
  'wardrobe, closet, press' : '衣装ダンス',
  'warplane, military plane' : '戦闘機',
  'washbasin, handbasin, washbowl, lavabo, wash-hand basin' : '洗面器',
  'washer, automatic washer, washing machine' : '洗濯機',
  'water bottle' : '水入れ、水筒',
  'water jug' : '水差し',
  'water tower' : '給水塔',
  'whiskey jug' : 'ウイスキーの水差し',
  'whistle' : 'ホイッスル',
  'wig' : 'かつら',
  'window screen' : '網戸',
  'window shade' : 'ブラインド',
  'Windsor tie' : 'ウィンザーネクタイ',
  'wine bottle' : 'ワインボトル',
  'wing' : '翼',
  'wok' : '中華鍋',
  'wooden spoon' : '木製スプーン',
  'wool, woolen, woollen' : 'ウール',
  'worm fence, snake fence, snake-rail fence, Virginia fence' : 'ワームフェンス',
  'wreck' : '難破',
  'yawl' : 'ヨール',
  'yurt' : 'ゲル',
  'web site, website, internet site, site' : 'ウェブサイト',
  'comic book' : 'マンガ',
  'crossword puzzle, crossword' : 'クロスワードパズル',
  'street sign' : '道路標識',
  'traffic light, traffic signal, stoplight' : '信号機',
  'book jacket, dust cover, dust jacket, dust wrapper' : 'ブックカバー',
  'menu' : 'メニュー',
  'plate' : 'プレート',
  'guacamole' : 'ワカモレ',
  'consomme' : 'コンソメ',
  'hot pot, hotpot' : '火鍋',
  'trifle' : 'トライフル',
  'ice cream, icecream' : 'アイスクリーム',
  'ice lolly, lolly, lollipop, popsicle' : 'アイスキャンディー',
  'French loaf' : 'フランスパン',
  'bagel, beigel' : 'ベーグル',
  'pretzel' : 'プレッツェル',
  'cheeseburger' : 'チーズバーガー',
  'hotdog, hot dog, red hot' : 'ホットドッグ',
  'mashed potato' : 'マッシュポテト',
  'head cabbage' : 'キャベツ',
  'broccoli' : 'ブロッコリ',
  'cauliflower' : 'カリフラワー',
  'zucchini, courgette' : 'ズッキーニ',
  'spaghetti squash' : 'キンシウリ',
  'acorn squash' : 'ドングリカボチャ',
  'butternut squash' : 'バターナット・スクウォッシュ',
  'cucumber, cuke' : 'キュウリ',
  'artichoke, globe artichoke' : 'アーティチョーク',
  'bell pepper' : 'ピーマン',
  'cardoon' : 'カルドン',
  'mushroom' : 'キノコ',
  'Granny Smith' : 'グラニースミス',
  'strawberry' : 'イチゴ',
  'orange' : 'オレンジ',
  'lemon' : 'レモン',
  'fig' : 'イチジク',
  'pineapple, ananas' : 'パイナップル',
  'banana' : 'バナナ',
  'jackfruit, jak, jack' : 'パラミツ',
  'custard apple' : 'バンレイシ',
  'pomegranate' : 'ザクロ',
  'hay' : '干し草',
  'carbonara' : 'カルボナーラ',
  'chocolate sauce, chocolate syrup' : 'チョコレートシロップ',
  'dough' : '生地',
  'meat loaf, meatloaf' : 'ミートローフ',
  'pizza, pizza pie' : 'ピザ',
  'potpie' : 'ポットパイ',
  'burrito' : 'ブリート',
  'red wine' : '赤ワイン',
  'espresso' : 'エスプレッソ',
  'cup' : 'カップ',
  'eggnog' : 'エッグノッグ',
  'alp' : '高山',
  'bubble' : '泡',
  'cliff, drop, drop-off' : '崖',
  'coral reef' : 'サンゴ礁',
  'geyser' : '間欠泉',
  'lakeside, lakeshore' : '湖畔',
  'promontory, headland, head, foreland' : '岬',
  'sandbar, sand bar' : '砂州',
  'seashore, coast, seacoast, sea-coast' : '海岸',
  'valley, vale' : '谷',
  'volcano' : '火山',
  'ballplayer, baseball player' : '野球選手',
  'groom, bridegroom' : '新郎',
  'scuba diver' : 'スキューバダイビング',
  'rapeseed' : 'セイヨウアブラナ',
  'daisy' : 'デイジー',
  'yellow lady\'s slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum' : 'カラフトアツモリソウ',
  'corn' : 'コーン',
  'acorn' : 'ドングリ',
  'hip, rose hip, rosehip' : 'ローズヒップ',
  'buckeye, horse chestnut, conker' : 'トチノキ',
  'coral fungus' : 'シロソウメンタケ',
  'agaric' : 'ハラタケ',
  'gyromitra' : 'シャグマアミガサタケ',
  'stinkhorn, carrion fungus' : 'スッポンタケ',
  'earthstar' : 'ヒメツチグリ',
  'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa' : 'マイタケ',
  'bolete' : 'ヤマドリタケ',
  'ear, spike, capitulum' : 'トウモロコシ',
  'toilet tissue, toilet paper, bathroom tissue' : 'トイレットペーパー'
};
